### ISSUE TITLE
IDL error leaves an interactive IDL-session open in pidly

### ISSUE THREAD

**Issue by ghost** [anthonyjsmith/pIDLy#4]
for example, when not having proper write-access to a directory, the following occurs when using pidly from ipython

In [1]: import pidly
In [2]: idl=pidly.IDL('/usr/bin/idl')
In [3]: idl('openw,lun,"foo",/get_lun')
% OPENW: Error opening file. Unit: 100, File: foo
  Permission denied
% Execution halted at: $MAIN$
IDL>

so, an interactive IDL-session remains active and pidly does not return back to python session. this is problematic when running python scripts from cron, leaving process running and not exiting properly.

**Comment by anthonyjsmith** [comment]
I'm going to close this - re-open if appropriate!
