### ISSUE TITLE
pIDLy does not work with multiprocessing

### ISSUE THREAD

**Issue by piyanatk** [anthonyjsmith/pIDLy#5]
I am trying to spawn multiple pidly sessions as child processes with multiprocessing, and it does not work. It might be related to [this issue](http://stackoverflow.com/questions/14899355/python-multiprocessing-valueerror-i-o-operation-on-closed-file).

```python
from multiprocessing import Pool
import pidly

def run(i):
    print i
    idl = pidly.IDL()
    idl.close()

pool = Pool(4)
pool.map(run, range(10))
pool.close()
pool.join()
```

if you execute the above scrip, you will get.
```
0
1
2
3
4
5
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    pool.map(run, range(10))
  File "/data2/piyanat/src/anaconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/data2/piyanat/src/anaconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: I/O operation on closed file
6
7
8
9
```

**Comment by anthonyjsmith** [comment]
No idea I'm afraid!

**Comment by piyanatk** [comment]
Okay. The problem was related to https://github.com/pexpect/pexpect/issues/86/. I had pexpect3.3 installed. After downgrading to 3.2, I was able to run the above codes with no issue.

**Comment by anthonyjsmith** [comment]
OK, I think I'll close this. Suspect it's too obscure a problem to mention on the README, but people can always find this issue if they end up Googling for the error message...
