### ISSUE TITLE
Error using pIDLy on Windows 

### ISSUE THREAD

**Issue by lorenzobernardi** [anthonyjsmith/pIDLy#6]
Hi all,
I'm trying to execute the following simple python script:

```
import pidly
print(pidly.__version__)
```

I have the following problem:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "E:\Sviluppo\PyCharm Community Edition 4.5.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python34\lib\site-packages\pidly.py", line 88, in <module>
    class IDL(pexpect.spawn):
AttributeError: 'module' object has no attribute 'spawn'
```

I have already correctly installed pidly and pexpect modules with the command:
`pip install pidly pexpect`
 and my working environment is:
- python 3.4
- windows 7
- idl 8.5 version

How can i solve this problem?
Thank you for any suggestion.
Lorenzo

**Comment by andreas-schreiber** [comment]
Should be a problem since pexpect is not meant to be used under windows with full compatibility. See https://pexpect.readthedocs.org/en/stable/overview.html#windows

> Pexpect on Windows
> New in version 4.0: Windows support
> 
> Pexpect can be used on Windows to wait for a pattern to be produced by a child process, using pexpect.popen_spawn.PopenSpawn, or a file descriptor, using pexpect.fdpexpect.fdspawn. This should be considered experimental for now.
> 
> pexpect.spawn and pexpect.run() are not available on Windows, as they rely on Unix pseudoterminals (ptys). Cross platform code must not use these.

**Comment by lorenzobernardi** [comment]
Thank you. 
Any solutions? Can i solve using some unix emulater, like git bash or other?

**Comment by andreas-schreiber** [comment]
You should ask the pexpect experts, but would not expect this to be solvable easily. I use therefore a VM with Linux inside, since Windows never was a good choice for doing using science tools.

**Comment by anthonyjsmith** [comment]
Thanks for the contributions! I'm not using IDL or Python these days, but (1) happy to receive contributions to the code, and (2) it seems that there is a built-in IDL/Python bridge these days, which seems to support Windows: http://www.exelisvis.com/docs/Python.html. Just discovered that today: anyone used it?

**Comment by andreas-schreiber** [comment]
Thanks, will try it next time needed.

**Comment by lorenzobernardi** [comment]
Dear all,
i'm trying with the simple following code:
from idlpy import IDL
import numpy.random as ran
```
e = IDL.ENVI()
#Generate the roi from a vector file
# Open a vector file
file_vec = IDL.Filepath('Sic_Trapani.shp', ROOT_DIR = """E:\\mydirectory\\shp\\""")
vettore = e.OpenVector(file_vec)
#Get the task from the catalog of ENVITasks
Task_VtoR = IDL.ENVITask('VectorRecordsToROI')
#Define inputs
IDL.Task_VtoR.INPUT_VECTOR = vettore
#Define outputs
Task_VtoR.OUTPUT_ROI_URI = IDL.Filepath('roi_roi.xml', ROOT_DIR = """mydirectory\\""")
#Run the task
IDL.Task_VtoR.Execute
```
I have several doubts about the:
```
e=IDL.ENVI()
vettore = e.OpenVector(file_vec)
```
lines and the IDL.Task using sintax.
Perhaps it would be better to use the python library to read the raster and the vector file and to extract the numeric information to be passed to the IDL.Task functions.
Any suggestions?
I will inform you about future developments or solutions.

Lorenzo

loreberna@gmail.com

**Comment by lorenzobernardi** [comment]
Update:

I have tryed:

```
IDL.ENVI()
vector=IDL.ENVI().OpenVector(file_vec)
```

The result is the following error message:

`Impossible find the access point 
??0LTISceneBuffer@LizardTech@@QEAA@AEBVLTIPixel@1@IIPEAPEAX@Z into the dynamic link library lti_DSDK.dll`

Like arab for me!!
I googled the error and i found this site:
Malware scan of gdal110.
Any suggestion?
Thanks

**Comment by anthonyjsmith** [comment]
Not sure this is related to pidly any more... try posting on stackoverflow?

**Comment by lorenzobernardi** [comment]
i did.
No answer.
it is a problem related to working with python and idl, but you are right.
Thank you

**Comment by anthonyjsmith** [comment]
I'm going to close this... re-open if appropriate!
